config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    resources :job_openings, only: [:index, :show, :new, :create]
    resources :job_applications, only: [:create]
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
	belongs_to :user, optional: true

	has_many :job_applications
	has_many :job_openings, through: :job_applications

	validates :first_name, presence: true, allow_blank: false
	validates :surname, presence: true, allow_blank: false

	def applied_to?(job_opening)
		job_openings.include?(job_opening)
	end
end

app/models/employer.rb
class Employer < ApplicationRecord
	belongs_to :user, optional: true

	validates :name, presence: true, allow_blank: false
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
	belongs_to :candidate
	belongs_to :job_opening

	validates :candidate, uniqueness: { scope: :job_opening, message: 'already applied' }
end

app/models/job_opening.rb
class JobOpening < ApplicationRecord
	belongs_to :employer

	has_many :job_applications
	has_many :candidates, through: :job_applications

	scope :for_employer, ->(employer) { where(employer: employer) }

	validates :title, presence: true, allow_blank: false
	validates :description, presence: true, allow_blank: false
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :validatable

  has_one :employer
  has_one :candidate

  def candidate?
    !!candidate
  end

  def employer?
    !!employer
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!

	def authenticate_candidate!
		authenticate_by_user_type!(:candidate)
	end

	def authenticate_employer!
		authenticate_by_user_type!(:employer)
	end

	private
		def authenticate_by_user_type!(user_type)
			authenticate_user!

			if !current_user.public_send("#{user_type}?")
				flash[:error] = "Only #{user_type}s can do this"
				redirect_back fallback_location: job_openings_path
			end
		end

		def after_sign_in_path_for(resource)
			job_openings_path
		end
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  before_action :authenticate_candidate!

  def create
    @job_application = JobApplication.new(job_application_params)
    @job_application.candidate = current_user.candidate

    if @job_application.save
      redirect_to job_openings_path, :flash => { success: "Job application was successfully created" }
    else
      redirect_to job_openings_path, :flash => { error: @job_application.errors.full_messages.first }
    end
  end

  private
    def job_application_params
      params.permit(:job_opening_id)
    end
end

app/controllers/job_openings_controller.rb
class JobOpeningsController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  before_action :authenticate_employer!, only: [:new, :create, :show]

  before_action :set_job_opening, only: [:show]

  def index
    if current_user.candidate?
      @job_openings = JobOpening.all.includes(:employer)
    elsif current_user.employer?
      @job_openings = JobOpening.for_employer(current_user.employer)
    end
  end

  def new
    @job_opening = JobOpening.new
  end

  def create
    @job_opening = JobOpening.new(job_opening_params)
    @job_opening.employer = current_user.employer

    if @job_opening.save
      flash[:success] = 'Job opening was successfully created'
      redirect_to job_openings_path
    else
      render :new
    end
  end

  private
    def set_job_opening
      @job_opening = JobOpening.find(params[:id])
    end

    def job_opening_params
      params.require(:job_opening).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
		case level
		when "success"
			"alert alert-success"
		when "error"
			"alert alert-danger"
		when "alert"
			"alert alert-danger"
		else
			"alert alert-info"
		end
	end
end

app/views/job_openings/_form.html.erb
<div class="border-form-div">
  <h2>New job opening</h2><% if job_opening.errors.any? %>
    <div class="alert alert-danger">
      <div>Error</div>
      <ul>
      <% job_opening.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for(job_opening, as: job_opening) do |f| %>
    <%= f.text_field :title, autofocus: true, placeholder: 'Title' %>
    <%= f.text_field :description, placeholder: 'Description' %>
    <%= f.submit "Create", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/job_openings/index.html.erb
<div class="container">
	<div class="page-header">
		<h1>Job Openings</h1>
	</div>
	<% if @current_user.employer? %>
		<div class="pull-right"><%= link_to 'Create new opening', new_job_opening_path, class: 'btn btn-success' %></div>
	<% end %>
	<% if @job_openings.any? %>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Title</th>
					<th>Description</th>
					<% if @current_user.candidate? %>
						<th>Employer</th>
					<% end %>
					<th class="text-center">Actions</th>
				</tr>
			</thead>
			<tbody>
				<% @job_openings.each do |job_opening| %>
					<tr>
						<td><%= job_opening.title %></td>
						<td><%= job_opening.description %></td>
						<% if @current_user.candidate? %>
							<td><%= job_opening.employer.name %></td>
							<td>
								<% if @current_user.candidate.applied_to?(job_opening) %>
									<span class="btn btn-default disabled btn-block">Applied</span>
								<% else %>
									<%= link_to 'Apply', job_applications_path(job_opening_id: job_opening.id), method: :post, class: 'btn btn-success btn-block' %>
								<% end %>
							</td>
						<% end %>
						<% if @current_user.employer? %>
							<td><%= link_to 'Show candidates', job_opening_path(job_opening), class: 'btn btn-info btn-block' %><td>
						<% end %>
					</tr>
				<% end %>
			</tbody>
		</table>
	<% else %>
		<div>There are no job openings</div>
	<% end %>
</div>

app/views/job_openings/new.html.erb
<%= render 'form', job_opening: @job_opening %>

app/views/job_openings/show.html.erb
<div class="container">
  <div class="page-header">
		<h1>Candidates</h1>
  </div>
  <p>Hi @<%= @current_user.employer.name %>, here are you candidates for '<%= @job_opening.title %>'</p>
  <div class="panel panel-default">
    <div class="panel-body">
      <% if @job_opening.candidates.any? %>
        <% @job_opening.candidates.each do |candidate| %>
          <hr />
          <div>Name: <%= "#{candidate.first_name} #{candidate.surname}" %></div>
        <% end %>
        <hr />
      <% else %>
        <div>There are no candidates 😭</div>
      <% end %>
    </div>
    <div class="panel-footer">
      <%= link_to 'Back', job_openings_path %>
    </div>
  </div>
</div>

app/views/layouts/_user_header.html.erb
<ul class="nav nav-pills pull-right">
  <% if user_signed_in? %>
    <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
  <% else %>
    <li><%= link_to "Sign in", new_user_session_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fountain</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <div class="container-narrow">
    <div class="masthead">
      <%= render 'layouts/user_header' %>
      <h3 class="muted"><%= link_to "Fountain", root_path %></h3>
    </div>
    <hr />
    <% flash.each do |key, value| %>
			<div class="<%= flash_class(key) %>">
				<%= value %>
			</div>
		<% end %>
    <%= yield %>
  </div>
  </body>
</html>